name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout Repo
        uses: actions/checkout@v3

      - name: 🚀 Deploy to VPS
        id: deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: roshit
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            bash ~/project/roshit-web-profile/deploy/deploy-web.sh

      - name: ✅ Notify Telegram on Success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ *Deploy Sukses*
            Project: roshit-web-profile
            VPS: ${{ secrets.VPS_HOST }}
            Branch: main
            Time: ${{ github.event.head_commit.timestamp }}

      - name: ❌ Notify Telegram on Failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ❌ *Deploy GAGAL*
            Cek CI log di GitHub Actions
            VPS: ${{ secrets.VPS_HOST }}
            Branch: main
